INSERT INTO role (id,name) values (100,'USER');
INSERT INTO user_entity (id,
                         email,
                         password,
                         full_name,
                         persist_date,
                         is_enabled,
                         is_deleted,
                         city,
                         link_site,
                         link_github,
                         link_vk,
                         about,
                         image_link,
                         last_redaction_date,
                         nickname,
                         role_id)
VALUES (
        100,
        'user100@mail.ru',
        '$2a$12$15IdweTSskIUYrtRI/hCc.yeds761vgRQ6rxoht1ILf23siw0TIBS', /*123*/
        'user100',
        CURRENT_TIMESTAMP,
        true,
        NULL,
        'user100_city',
        'user100site.com',
        'user100github.com',
        'user100vk.com',
        'test_user100',
        '\image_user100.jpg',
        CURRENT_TIMESTAMP,
        'user100',
        100),
       (101,
        'user101@mail.ru',
        '$2a$12$15IdweTSskIUYrtRI/hCc.yeds761vgRQ6rxoht1ILf23siw0TIBS', /*123*/
        'user101',
        '2022-02-12T17:05:24.197649',
        true,
        NULL,
        'user101_city',
        'user101site.com',
        'user101github.com',
        'user101vk.com',
        'test_user101',
        '\image_user101.jpg',
        CURRENT_TIMESTAMP,
        'user101',
        100),
       (102,
        'user102@mail.ru',
        '$2a$12$15IdweTSskIUYrtRI/hCc.yeds761vgRQ6rxoht1ILf23siw0TIBS', /*123*/
        'user102',
        '2022-03-12T17:05:24.197649',
        true,
        NULL,
        'user102_city',
        'user102site.com',
        'user102github.com',
        'user102vk.com',
        'test_user102',
        '\image_user102.jpg',
        CURRENT_TIMESTAMP,
        'user102',
        100);

INSERT INTO question (id,
                      title,
                      description,
                      persist_date,
                      user_id,
                      last_redaction_date,
                      is_deleted)
VALUES (100,
        'Question_100',
        'Question from user100',
        CURRENT_TIMESTAMP,
        100,
        CURRENT_TIMESTAMP,
        FALSE
       );

INSERT INTO reputation (id,
                        persist_date,
                        author_id,
                        sender_id,
                        count,
                        --type,
                        question_id,
                        answer_id
)
VALUES (100,
        CURRENT_TIMESTAMP,
        100,
        101,
        10,
        --'Question',
        100,
        null
       ),
       (101,
        CURRENT_TIMESTAMP,
        100,
        102,
        -5,
        --'Question',
        100,
        null);



