create sequence user_chat_pin_seq start 1 increment 1;

CREATE TABLE user_chat_pin
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    chat_id    BIGINT                                  NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_chat_pin PRIMARY KEY (id)
);

ALTER TABLE user_chat_pin
    ADD CONSTRAINT FK_USER_CHAT_PIN_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);
ALTER TABLE user_chat_pin
    ADD CONSTRAINT FK_USER_CHAT_PIN_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);